module.exports = {
    nomeUsuario: "O nome do usuário é obrigatório!",
    cpfUsuario: "O cpf do usuário é obrigatório!",
    dataNascimento: "A data de nascimento do usuário é obrigatória!",
    telefone: "O telefone do usuário é obrigatório!",
    emailUsuario: "O email do usuário é obrigatório!",
    senhaUsuario: "A senha do usuário é obrigatória!",
    conta: "O número da conta é obrigatório!" ,
    valor: "O valor é obrigatório!",
    senha: "A senha da conta é obrigatória!",
    senhaBanco: "A senha do banco é obrigatória!",
    senhaBancoInvalida: "A senha do banco informada é inválida!",
    contaNaoEncontrada: "Conta bancária não encontrada!",
    contaDuplicada: "Já existe uma conta com o cpf ou e-mail informado!",
    cpfDuplicado: "O CPF informado já existe cadastrado!",
    emailDuplicado: "O email informado já existe cadastrado!",
    valorInvalido: "O valor não pode ser menor que 0!",
    senhaIncorreta: "A senha informada é inválida!",
    contaOrigem: "O número da conta de origem é obrigatório!",
    contaOrigemNaoEncontrada: "Conta de origem não encontrada!",
    contaDestino: "O número da conta de destino é obrigatório!",
    contaDestinoNaoEncontrada: "Conta destino não encontrada!",
    contasIguais: "Não é permitido efetuar transferências para a conta de saída!",
    saldoIndisponivel: "Saldo insuficiente!",
    saldoInvalido: "A conta só pode ser removida se o saldo for zero!"
}
